In [35]:
aodb = pd.read_csv('Target-list-with-orbital-params.csv')
aodb

pl_name  pl_orbsmax   pl_orbper  pl_orbincl  pl_orbeccen  \
0    Proxima Cen d     0.02881     5.12338         NaN        0.000   
1    Proxima Cen b     0.04848    11.18465         NaN        0.000   
2        Barnard c     0.02740     4.12440         NaN        0.080   
3        Barnard e     0.03810     6.73920         NaN        0.040   
4        Barnard b     0.02290     3.15420         NaN        0.030   
..             ...         ...         ...         ...          ...   
711     HD 66141 b     1.20000   480.50000         NaN        0.070   
712    HD 143361 b     1.98800  1039.15000        50.0        0.197   
713    HD 179079 b     0.12140    14.47900         NaN        0.049   
714     HD 72892 b     0.22800    39.44603         NaN        0.419   
715      eps CrB b     1.30000   417.90000         NaN        0.110   

       pl_bmasse  pl_bmassj  st_mass   sy_dist  PlanetRadiuse  ...  \
0       0.260000   0.000818   0.1221   1.30119          0.692  ...   
1       1.055000   0.003319   0.1221   1.30119          1.020  ...   
2       0.335000   0.001054   0.1620   1.82655          0.743  ...   
3       0.193000   0.000607   0.1620   1.82655          0.637  ...   
4       0.299000   0.000941   0.1620   1.82655          0.720  ...   
..           ...        ...      ...       ...            ...  ...   
711  1906.900000   6.000000   1.1000  68.15090         12.800  ...   
712  1382.553570   4.350000   0.9680  68.51460         12.900  ...   
713    25.744230   0.081000   1.1400  69.71160          5.480  ...   
714  1737.885729   5.468000   1.0100  69.73110         12.800  ...   
715  2129.461000   6.700000   1.7000  69.86830         12.700  ...   

     TypicalCont_elt  TypicalSeparation_lod_magaox  TypicalPhase_magaox  \
0       3.406633e-07                      0.681558            55.630047   
1       2.613789e-07                      1.024218            47.846627   
2       3.801625e-07                      0.554964            71.968280   
3       1.713371e-07                      0.660260            58.771266   
4       5.833585e-07                      0.505654            88.076143   
..               ...                           ...                  ...   
711     6.510187e-08                      0.606618            65.288814   
712     3.299299e-08                      0.756359            53.664335   
713              NaN                           NaN                  NaN   
714     1.414476e-06                           NaN                  NaN   
715     5.032690e-08                      0.628413            61.425742   

     TypicalCont_magaox  TypicalSeparation_mas_gmagaox  \
0          3.073979e-07                      15.454116   
1          2.613789e-07                      26.005690   
2          2.807511e-07                      11.109656   
3          1.464828e-07                      14.322754   
4          2.568082e-07                       8.754227   
..                  ...                            ...   
711        5.121656e-08                      12.472487   
712        3.299299e-08                      19.204527   
713                 NaN                            NaN   
714                 NaN                       3.901131   
715        4.349583e-08                      13.673755   

     TypicalSeparation_au_gmagaox  TypicalSeparation_mas_elt  \
0                        0.020109                  15.454116   
1                        0.033838                  26.005690   
2                        0.020292                  11.109656   
3                        0.026161                  14.322754   
4                        0.015990                   8.754227   
..                            ...                        ...   
711                      0.850011                  12.472487   
712                      1.315790                  19.204527   
713                           NaN                        NaN   
714                      0.272030                   3.040241   
715            

In [2]:
aodb.columns

Index(['pl_name', 'pl_orbsmax', 'pl_orbper', 'pl_orbincl', 'pl_orbeccen',
       'pl_bmasse', 'pl_bmassj', 'st_mass', 'sy_dist', 'PlanetRadiuse',
       'pl_orblper', 'StarTeff', 'st_logg', 'st_met', 'StarRad', 'sy_imag',
       'sy_gaiamag', 'rastr', 'ra', 'decstr', 'dec', 'SpTNumber',
       'MaxProjectedSeparation_au', 'MaxProjectedSeparation_mas',
       'PhaseAtMaxProj', 'ContrastAtMaxProj', 'MaxProjectedSeparation_lod_elt',
       'MaxProjectedSeparation_lod_gmagaox',
       'MaxProjectedSeparation_lod_magaox', 'SepsInPlaneOfSky_au',
       'SepsInPlaneOfOrbit_au', 'Contrasts', 'Phases', 'SepsInPlaneOfSky_mas',
       'SepsInPlaneOfSky_lod_magaox', 'SepsInPlaneOfSky_lod_gmagaox',
       'SepsInPlaneOfSky_lod_elt', 'TypicalSeparation_lod_gmagaox',
       'TypicalPhase_gmagaox', 'TypicalCont_gmagaox',
       'TypicalSeparation_lod_elt', 'TypicalPhase_elt', 'TypicalCont_elt',
       'TypicalSeparation_lod_magaox', 'TypicalPhase_magaox',
       'TypicalCont_magaox', 'TypicalSeparatio

In [13]:
venus = ['HD 20794 d', 'HD 219134 d', 'GJ 411 b', 'HD 219134 f', 'Proxima Cen d', 'Barnard e', 'Wolf 1061 c', 'GJ 15 A b',
             'Gl 725 A b', 'GJ 273 b', 'Barnard c', 'GJ 1061 d', 'Ross 128 b', 'GJ 251 b', 'Barnard b', 'GJ 625 b', 'Barnard d', 
             'L 98-59 f', 'GJ 1061 c', 'AU Mic d']
for i,v in enumerate(venus):
    print(i,[aodb['pl_name'][i] for i in range(len(aodb)) if v in aodb['pl_name'][i]])
    if len([aodb['pl_name'][i] for i in range(len(aodb)) if v in aodb['pl_name'][i]]) == 0:
        print(v)

0 ['HD 20794 d']
1 ['HD 219134 d']
2 ['GJ 411 b']
3 ['HD 219134 f']
4 ['Proxima Cen d']
5 ['Barnard e']
6 ['Wolf 1061 c']
7 ['GJ 15 A b']
8 ['Gl 725 A b']
9 []
GJ 273 b
10 ['Barnard c']
11 ['GJ 1061 d']
12 []
Ross 128 b
13 ['GJ 251 b']
14 ['Barnard b']
15 ['GJ 625 b']
16 ['Barnard d']
17 []
L 98-59 f
18 ['GJ 1061 c']
19 []
AU Mic d


In [18]:
andes = ['Proxima Cen b', 'GJ 273 b', 'Wolf 1061 c', 'GJ 682 b', 'Ross 128 b']
for i,v in enumerate(andes):
    print(i,[aodb['pl_name'][i] for i in range(len(aodb)) if v in aodb['pl_name'][i]])
    if len([aodb['pl_name'][i] for i in range(len(aodb)) if v in aodb['pl_name'][i]]) == 0:
        print(v)

0 ['Proxima Cen b']
1 []
GJ 273 b
2 ['Wolf 1061 c']
3 ['GJ 682 b']
4 []
Ross 128 b


In [26]:
aodb.loc[ind[0],'Note'] == ''
#ind

True

In [36]:
aodb['Note'] = ''
names = np.array(aodb['pl_name'])
plandb = pd.read_csv('plandb.csv')

#try:
ind = np.array([], dtype=int)
for name in plandb['pl_name']:
    try:
        ind = np.append(ind,int(np.where(names == name)[0][0]))
    except IndexError:
        pass
aodb.loc[ind,'Note']='In Imaging Mission Database'

andes = ['Proxima Cen b', 'GJ 273 b', 'Wolf 1061 c', 'GJ 682 b', 'Ross 128 b']
ind = np.array([], dtype=int)
for name in andes:
    try:
        ind = np.append(ind,int(np.where(names == name)[0][0]))
        print(ind)
        indtemp = int(np.where(names == name)[0][0])
        print(indtemp)
        if aodb.loc[indtemp,'Note'] == '':
            aodb.loc[indtemp,'Note'] = 'In ELT-ANDES Golden Sample for Atm Characterization'
        else:
            aodb.loc[indtemp,'Note'] = aodb.loc[indtemp,'Note']+'; In ELT-ANDES Golden Sample for Atm Characterization'
    except IndexError:
        pass


venus = ['HD 20794 d', 'HD 219134 d', 'GJ 411 b', 'HD 219134 f', 'Proxima Cen d', 'Barnard e', 'Wolf 1061 c', 'GJ 15 A b',
             'Gl 725 A b', 'GJ 273 b', 'Barnard c', 'GJ 1061 d', 'Ross 128 b', 'GJ 251 b', 'Barnard b', 'GJ 625 b', 'Barnard d', 
             'L 98-59 f', 'GJ 1061 c', 'AU Mic d']

ind = np.array([], dtype=int)
for name in venus:
    try:
        ind = np.append(ind,int(np.where(names == name)[0][0]))
        indtemp = int(np.where(names == name)[0][0])
        print(ind)
        if aodb.loc[indtemp,'Note'] == '':
            aodb.loc[indtemp,'Note'] = 'In Kane+2026 Venus Zone'
        else:
            aodb.loc[indtemp,'Note'] = aodb.loc[indtemp,'Note']+'; In Kane+2026 Venus Zone'
    except IndexError:
        pass

[1]
1
[ 1 26]
26
[ 1 26 36]
36
[44]
[44 56]
[44 56 39]
[44 56 39 54]
[44 56 39 54  0]
[44 56 39 54  0  3]
[44 56 39 54  0  3 26]
[44 56 39 54  0  3 26  9]
[44 56 39 54  0  3 26  9  7]
[44 56 39 54  0  3 26  9  7  2]
[44 56 39 54  0  3 26  9  7  2 15]
[44 56 39 54  0  3 26  9  7  2 15 38]
[44 56 39 54  0  3 26  9  7  2 15 38  4]
[44 56 39 54  0  3 26  9  7  2 15 38  4 51]
[44 56 39 54  0  3 26  9  7  2 15 38  4 51  5]
[44 56 39 54  0  3 26  9  7  2 15 38  4 51  5 17]


In [31]:
aodb

pl_name  pl_orbsmax   pl_orbper  pl_orbincl  pl_orbeccen  \
0    Proxima Cen d     0.02881     5.12338         NaN        0.000   
1    Proxima Cen b     0.04848    11.18465         NaN        0.000   
2        Barnard c     0.02740     4.12440         NaN        0.080   
3        Barnard e     0.03810     6.73920         NaN        0.040   
4        Barnard b     0.02290     3.15420         NaN        0.030   
..             ...         ...         ...         ...          ...   
711     HD 66141 b     1.20000   480.50000         NaN        0.070   
712    HD 143361 b     1.98800  1039.15000        50.0        0.197   
713    HD 179079 b     0.12140    14.47900         NaN        0.049   
714     HD 72892 b     0.22800    39.44603         NaN        0.419   
715      eps CrB b     1.30000   417.90000         NaN        0.110   

       pl_bmasse  pl_bmassj  st_mass   sy_dist  PlanetRadiuse  ...  \
0       0.260000   0.000818   0.1221   1.30119          0.692  ...   
1       1.055000   0.003319   0.1221   1.30119          1.020  ...   
2       0.335000   0.001054   0.1620   1.82655          0.743  ...   
3       0.193000   0.000607   0.1620   1.82655          0.637  ...   
4       0.299000   0.000941   0.1620   1.82655          0.720  ...   
..           ...        ...      ...       ...            ...  ...   
711  1906.900000   6.000000   1.1000  68.15090         12.800  ...   
712  1382.553570   4.350000   0.9680  68.51460         12.900  ...   
713    25.744230   0.081000   1.1400  69.71160          5.480  ...   
714  1737.885729   5.468000   1.0100  69.73110         12.800  ...   
715  2129.461000   6.700000   1.7000  69.86830         12.700  ...   

     TypicalSeparation_lod_magaox  TypicalPhase_magaox  TypicalCont_magaox  \
0                        0.681558            55.630047        3.073979e-07   
1                        1.024218            47.846627        2.613789e-07   
2                        0.554964            71.968280        2.807511e-07   
3                        0.660260            58.771266        1.464828e-07   
4                        0.505654            88.076143        2.568082e-07   
..                            ...                  ...                 ...   
711                      0.606618            65.288814        5.121656e-08   
712                      0.756359            53.664335        3.299299e-08   
713                           NaN                  NaN                 NaN   
714                           NaN                  NaN                 NaN   
715                      0.628413            61.425742        4.349583e-08   

     TypicalSeparation_mas_gmagaox  TypicalSeparation_au_gmagaox  \
0                        15.454116                      0.020109   
1                        26.005690                      0.033838   
2                        11.109656                      0.020292   
3                        14.322754                      0.026161   
4                         8.754227                      0.015990   
..                             ...                           ...   
711                      12.472487                      0.850011   
712                      19.204527                      1.315790   
713                            NaN                           NaN   
714                       3.901131                      0.272030   
715                      13.673755                      0.955362   

     TypicalSeparation_mas_elt  TypicalSeparation_au_elt  \
0                    15.454116                  0.020109   
1                    26.005690                  0.033838   
2                    11.109656                  0.020292   
3                    14.322754                  0.026161   
4                     8.754227                  0.015990   
..                         ...                       ...   
711                  12.472487                  0.850011   
712                  19.204527                  1.315790   
713                    

In [37]:
aodb.to_csv('Target-list-with-orbital-params.csv', index=False)

In [39]:
orbits = pd.read_csv('Target-list-with-orbital-params.csv')
orbits.columns

Index(['pl_name', 'pl_orbsmax', 'pl_orbper', 'pl_orbincl', 'pl_orbeccen',
       'pl_bmasse', 'pl_bmassj', 'st_mass', 'sy_dist', 'PlanetRadiuse',
       'pl_orblper', 'StarTeff', 'st_logg', 'st_met', 'StarRad', 'sy_imag',
       'sy_gaiamag', 'rastr', 'ra', 'decstr', 'dec', 'SpTNumber',
       'MaxProjectedSeparation_au', 'MaxProjectedSeparation_mas',
       'PhaseAtMaxProj', 'ContrastAtMaxProj', 'MaxProjectedSeparation_lod_elt',
       'MaxProjectedSeparation_lod_gmagaox',
       'MaxProjectedSeparation_lod_magaox', 'SepsInPlaneOfSky_au',
       'SepsInPlaneOfOrbit_au', 'Contrasts', 'Phases', 'SepsInPlaneOfSky_mas',
       'SepsInPlaneOfSky_lod_magaox', 'SepsInPlaneOfSky_lod_gmagaox',
       'SepsInPlaneOfSky_lod_elt', 'TypicalSeparation_lod_gmagaox',
       'TypicalPhase_gmagaox', 'TypicalCont_gmagaox',
       'TypicalSeparation_lod_elt', 'TypicalPhase_elt', 'TypicalCont_elt',
       'TypicalSeparation_lod_magaox', 'TypicalPhase_magaox',
       'TypicalCont_magaox', 'TypicalSeparatio

In [40]:
koppDict = {
    1:{'Seff':1.776,1.107,0.356,0.32}
}


0         0.260000
1         1.055000
2         0.299000
3         0.263000
4         0.193000
          ...     
931      11.320000
932    4195.334972
933    1737.885729
934       7.400000
935    2129.461000
Name: pl_bmasse, Length: 936, dtype: float64